-- =============================================================================
-- IS Studio: normalised schema (target of the workspace_data migration)
-- =============================================================================
--
-- Replaces the single-row JSONB document (workspace_data id='default') with
-- typed tables. supabase-setup.sql still describes what runs today; this file
-- is additive and does not touch workspace_data.
--
-- Safe to run more than once: tables are created only if missing, app_users is
-- extended with ADD COLUMN IF NOT EXISTS, and seed rows are inserted only when
-- absent.
--
-- PORTABILITY. Written for PostgreSQL (Supabase) in SQL that carries across
-- with mechanical substitutions. SQL Server equivalents:
--   BIGINT GENERATED BY DEFAULT AS IDENTITY  ->  BIGINT IDENTITY(1,1)
--     (standard SQL; the BIGSERIAL shorthand is deliberately not used)
--   TIMESTAMPTZ                              ->  DATETIMEOFFSET
--   NUMERIC(p,s)                             ->  DECIMAL(p,s)
--   BOOLEAN / TRUE / FALSE                   ->  BIT / 1 / 0
--   TEXT                                     ->  NVARCHAR(MAX)
--   VARCHAR(n)                               ->  NVARCHAR(n)
--   CURRENT_TIMESTAMP                        ->  SYSDATETIMEOFFSET()
--   CREATE TABLE IF NOT EXISTS               ->  IF OBJECT_ID('t') IS NULL CREATE TABLE ...
--   CREATE INDEX IF NOT EXISTS               ->  IF NOT EXISTS (SELECT 1 FROM sys.indexes ...) CREATE INDEX ...
--   ALTER TABLE .. ADD COLUMN IF NOT EXISTS  ->  IF COL_LENGTH('t','c') IS NULL ALTER TABLE t ADD c ...
--   INSERT ... ON CONFLICT (upsert)          ->  MERGE
--     (not used here: seeds use INSERT ... SELECT ... WHERE NOT EXISTS, which
--      both engines accept; the migration's upserts are ON CONFLICT underneath)
--
-- Conventions: no enums (CHECK constraints instead), no arrays, no JSONB. Every
-- list that used to be an array is a child table with a position column.
--
-- Access model: IT is one shared team across the group. company_id is a
-- reporting and filtering dimension, not a security boundary, so there are no
-- per-company row rules.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- GROUP
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS companies (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Short code used in document numbers, e.g. REQ-EDC-0042.
  code        VARCHAR(16)  NOT NULL UNIQUE,
  name        VARCHAR(200) NOT NULL,
  active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Replaces free-text locations ("Level 2", "L2", "HQ - Procurement"), so work
-- can be reported by site.
CREATE TABLE IF NOT EXISTS sites (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  BIGINT       NOT NULL REFERENCES companies (id),
  code        VARCHAR(32),
  name        VARCHAR(200) NOT NULL,
  active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_sites_company_name UNIQUE (company_id, name)
);

-- The IT category list, moved out of code so a company can add or retire one
-- without a redeploy. company_id NULL means the category applies group-wide;
-- otherwise it is offered only to that company. Names are unique group-wide
-- (a composite unique on a nullable column behaves differently across engines).
CREATE TABLE IF NOT EXISTS categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL UNIQUE,
  company_id  BIGINT       REFERENCES companies (id),
  sort_order  INTEGER      NOT NULL DEFAULT 0,
  active      BOOLEAN      NOT NULL DEFAULT TRUE
);


-- -----------------------------------------------------------------------------
-- PEOPLE
-- -----------------------------------------------------------------------------
-- app_users already exists (supabase-setup.sql) and holds live accounts. It is
-- extended, never recreated. Its TEXT primary key is kept as-is, so every
-- foreign key to a user is VARCHAR(64).
-- The unused avatar column is left for a separate, deliberate DROP.

ALTER TABLE app_users ADD COLUMN IF NOT EXISTS company_id BIGINT REFERENCES companies (id);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS site_id    BIGINT REFERENCES sites (id);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS phone_ext  VARCHAR(32);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS active     BOOLEAN NOT NULL DEFAULT TRUE;


-- -----------------------------------------------------------------------------
-- HANDBOOK
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS runbooks (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The id from the JSON document ("runbook-..."), kept so the migration can
  -- be re-run without duplicating. NULL for guides created after cutover.
  legacy_id           VARCHAR(64)  UNIQUE,
  code                VARCHAR(32)  NOT NULL UNIQUE,
  title               VARCHAR(300) NOT NULL,
  category_id         BIGINT       REFERENCES categories (id),
  -- Most guides apply group-wide; some to one company or one site.
  scope               VARCHAR(10)  NOT NULL DEFAULT 'group',
  company_id          BIGINT       REFERENCES companies (id),
  site_id             BIGINT       REFERENCES sites (id),
  status              VARCHAR(12)  NOT NULL DEFAULT 'active',
  version             VARCHAR(20)  NOT NULL DEFAULT '1.0.0',
  -- Free text: an author may be a team or an outside vendor, not an app user.
  author_name         VARCHAR(200),
  author_role         VARCHAR(200),
  symptom             TEXT,
  root_cause_analysis TEXT,
  rollback_plan       TEXT,
  last_updated        DATE,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_runbooks_scope  CHECK (scope IN ('group', 'company', 'site')),
  CONSTRAINT ck_runbooks_status CHECK (status IN ('active', 'draft', 'deprecated')),
  -- Scope and ids must agree: group has neither, company has only company_id,
  -- site has both.
  CONSTRAINT ck_runbooks_scope_ids CHECK (
       (scope = 'group'   AND company_id IS NULL     AND site_id IS NULL)
    OR (scope = 'company' AND company_id IS NOT NULL AND site_id IS NULL)
    OR (scope = 'site'    AND company_id IS NOT NULL AND site_id IS NOT NULL)
  )
);

-- Staff-language tags the IT Assistant matches against.
CREATE TABLE IF NOT EXISTS runbook_tags (
  runbook_id  BIGINT       NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  tag         VARCHAR(100) NOT NULL,
  PRIMARY KEY (runbook_id, tag)
);

-- Literal error text users paste ("Matched Alert Patterns").
CREATE TABLE IF NOT EXISTS runbook_trigger_patterns (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runbook_id  BIGINT  NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  position    INTEGER NOT NULL,
  pattern     TEXT    NOT NULL,
  CONSTRAINT uq_runbook_trigger_patterns UNIQUE (runbook_id, position)
);

CREATE TABLE IF NOT EXISTS runbook_diagnostic_steps (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runbook_id  BIGINT       NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  position    INTEGER      NOT NULL,
  title       VARCHAR(300) NOT NULL,
  explanation TEXT,
  cli         TEXT,
  shell_type  VARCHAR(12)  NOT NULL DEFAULT 'general',
  CONSTRAINT uq_runbook_diagnostic_steps UNIQUE (runbook_id, position),
  CONSTRAINT ck_runbook_diagnostic_shell CHECK (shell_type IN ('general', 'powershell', 'bash', 'sql', 'kubectl', 'docker'))
);

CREATE TABLE IF NOT EXISTS runbook_remediation_steps (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runbook_id   BIGINT       NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  -- Display order; the "Step N" number shown is this position.
  position     INTEGER      NOT NULL,
  title        VARCHAR(300) NOT NULL,
  instruction  TEXT,
  command      TEXT,
  dangerous    BOOLEAN      NOT NULL DEFAULT FALSE,
  verification TEXT,
  CONSTRAINT uq_runbook_remediation_steps UNIQUE (runbook_id, position)
);

CREATE TABLE IF NOT EXISTS runbook_postmortem_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runbook_id  BIGINT  NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  position    INTEGER NOT NULL,
  item        TEXT    NOT NULL,
  CONSTRAINT uq_runbook_postmortem_items UNIQUE (runbook_id, position)
);

-- Review notes from the AI SOP Writer: gaps still to confirm, and named
-- placeholders standing in for real values. Not in the original 26-table
-- plan; added because live guides carry these lists and they would otherwise
-- be lost. A guide stays draft while any needs_confirming row remains.
CREATE TABLE IF NOT EXISTS runbook_review_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  runbook_id  BIGINT      NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  kind        VARCHAR(20) NOT NULL,
  position    INTEGER     NOT NULL,
  note        TEXT        NOT NULL,
  CONSTRAINT uq_runbook_review_items UNIQUE (runbook_id, kind, position),
  CONSTRAINT ck_runbook_review_items_kind CHECK (kind IN ('needs_confirming', 'placeholder'))
);


-- -----------------------------------------------------------------------------
-- TICKETS
-- -----------------------------------------------------------------------------

-- Next number per company and document prefix, so each company numbers
-- independently (REQ-EDC-0042, REQ-KH-0042). Form prefixes (UID, IRQ, ALC,
-- DSP) share the table. Numbers already issued are never changed.
CREATE TABLE IF NOT EXISTS ticket_sequences (
  company_id  BIGINT      NOT NULL REFERENCES companies (id),
  prefix      VARCHAR(16) NOT NULL,
  last_value  INTEGER     NOT NULL DEFAULT 0,
  PRIMARY KEY (company_id, prefix),
  CONSTRAINT ck_ticket_sequences_nonnegative CHECK (last_value >= 0)
);

CREATE TABLE IF NOT EXISTS tickets (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id         VARCHAR(64)  UNIQUE,
  company_id        BIGINT       NOT NULL REFERENCES companies (id),
  ticket_number     VARCHAR(40)  NOT NULL,
  title             VARCHAR(300) NOT NULL,
  description       TEXT,
  raw_logs          TEXT,
  error_signature   VARCHAR(500),
  status            VARCHAR(16)  NOT NULL DEFAULT 'backlog',
  category_id       BIGINT       REFERENCES categories (id),
  -- References instead of copied {name, role, email} objects, so renaming a
  -- technician does not make history contradict the staff list.
  requester_id      VARCHAR(64)  REFERENCES app_users (id),
  assignee_id       VARCHAR(64)  REFERENCES app_users (id),
  site_id           BIGINT       REFERENCES sites (id),
  device_info       VARCHAR(300),
  phone_ext         VARCHAR(32),
  hod_name          VARCHAR(200),
  hod_email         VARCHAR(320),
  is_user_submitted BOOLEAN      NOT NULL DEFAULT FALSE,
  incident_summary  TEXT,
  resolution_notes  TEXT,
  due_date          TIMESTAMPTZ,
  resolved_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_tickets_company_number UNIQUE (company_id, ticket_number),
  CONSTRAINT ck_tickets_status CHECK (status IN ('backlog', 'investigating', 'in_progress', 'blocked', 'testing', 'done'))
);

CREATE TABLE IF NOT EXISTS ticket_tags (
  ticket_id  BIGINT       NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
  -- automated: set by triage/submission; manual: added by a technician.
  source     VARCHAR(10)  NOT NULL,
  tag        VARCHAR(100) NOT NULL,
  PRIMARY KEY (ticket_id, source, tag),
  CONSTRAINT ck_ticket_tags_source CHECK (source IN ('automated', 'manual'))
);

CREATE TABLE IF NOT EXISTS ticket_checklist_items (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id  BIGINT       NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
  position   INTEGER      NOT NULL,
  item_text  VARCHAR(500) NOT NULL,
  done       BOOLEAN      NOT NULL DEFAULT FALSE,
  command    TEXT,
  CONSTRAINT uq_ticket_checklist_items UNIQUE (ticket_id, position)
);

CREATE TABLE IF NOT EXISTS ticket_status_history (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id      BIGINT       NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
  -- NULL for the first recorded state.
  from_status    VARCHAR(16),
  to_status      VARCHAR(16)  NOT NULL,
  changed_by_id  VARCHAR(64)  REFERENCES app_users (id),
  changed_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note           VARCHAR(300),
  CONSTRAINT ck_ticket_status_history_from CHECK (from_status IS NULL OR from_status IN ('backlog', 'investigating', 'in_progress', 'blocked', 'testing', 'done')),
  CONSTRAINT ck_ticket_status_history_to   CHECK (to_status IN ('backlog', 'investigating', 'in_progress', 'blocked', 'testing', 'done'))
);

-- Tickets a guide relates to. Covers both directions the document stored:
-- runbook.relatedTaskIds and task.linkedRunbookId.
CREATE TABLE IF NOT EXISTS runbook_related_tickets (
  runbook_id  BIGINT NOT NULL REFERENCES runbooks (id) ON DELETE CASCADE,
  ticket_id   BIGINT NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
  PRIMARY KEY (runbook_id, ticket_id)
);


-- -----------------------------------------------------------------------------
-- FORMS
-- -----------------------------------------------------------------------------

-- One row per submitted form, carrying what all the paper forms share: the
-- applicant block and the attachment declaration. Per-type tables below hold
-- only what is unique to each form.
CREATE TABLE IF NOT EXISTS form_submissions (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id         VARCHAR(64)  UNIQUE,
  company_id        BIGINT       NOT NULL REFERENCES companies (id),
  form_number       VARCHAR(40)  NOT NULL,
  form_type         VARCHAR(12)  NOT NULL,
  submitted_by_id   VARCHAR(64)  REFERENCES app_users (id),
  submitted_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Applicant block. The person the form is for may differ from the submitter.
  requestor_name    VARCHAR(200),
  phone_ext         VARCHAR(32),
  designation       VARCHAR(200),
  department        VARCHAR(200),
  request_date      DATE,
  site_id           BIGINT       REFERENCES sites (id),
  -- Attachment declaration. NULL when the form did not ask or it was left blank.
  has_attachments   VARCHAR(3),
  attachment_format VARCHAR(10),
  -- Workflow in the admin Form Inbox.
  viewed_at         TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ,
  completed_by_id   VARCHAR(64)  REFERENCES app_users (id),
  rejected_at       TIMESTAMPTZ,
  rejected_by_id    VARCHAR(64)  REFERENCES app_users (id),
  rejection_reason  TEXT,
  CONSTRAINT uq_form_submissions_company_number UNIQUE (company_id, form_number),
  CONSTRAINT ck_form_submissions_type   CHECK (form_type IN ('user-id', 'requisition', 'disposal', 'allocation')),
  CONSTRAINT ck_form_submissions_has_attachments CHECK (has_attachments IS NULL OR has_attachments IN ('yes', 'no')),
  CONSTRAINT ck_form_submissions_attachment_format CHECK (attachment_format IS NULL OR attachment_format IN ('hardcopy', 'softcopy')),
  -- A form is either done or rejected, never both.
  CONSTRAINT ck_form_submissions_one_outcome CHECK (completed_at IS NULL OR rejected_at IS NULL),
  -- Only the IT Hardware, Software & Peripherals Requisition can be rejected.
  CONSTRAINT ck_form_submissions_reject_type CHECK (rejected_at IS NULL OR form_type = 'requisition')
);

-- New User ID Requisition.
CREATE TABLE IF NOT EXISTS form_user_id (
  submission_id  BIGINT PRIMARY KEY REFERENCES form_submissions (id) ON DELETE CASCADE,
  -- Write-in value for the "Others:" system.
  others_detail  VARCHAR(300),
  remarks        TEXT
);

-- Systems on the User ID form. Rows are referenced by id, not by position, so
-- reordering the on-screen list never changes the meaning of past submissions.
CREATE TABLE IF NOT EXISTS form_system_options (
  id             VARCHAR(40)  PRIMARY KEY,
  label          VARCHAR(100) NOT NULL,
  has_free_text  BOOLEAN      NOT NULL DEFAULT FALSE,
  sort_order     INTEGER      NOT NULL DEFAULT 0,
  active         BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS form_user_id_systems (
  submission_id  BIGINT      NOT NULL REFERENCES form_user_id (submission_id) ON DELETE CASCADE,
  option_id      VARCHAR(40) NOT NULL REFERENCES form_system_options (id),
  PRIMARY KEY (submission_id, option_id)
);

-- IT Hardware, Software & Peripherals Requisition.
-- Amounts are typed as text on screen (so partial input is not lost) and parsed
-- to numbers when saved.
CREATE TABLE IF NOT EXISTS form_requisition (
  submission_id     BIGINT PRIMARY KEY REFERENCES form_submissions (id) ON DELETE CASCADE,
  -- The IT/IR/__/__/__ reference written on the paper form.
  ref_no            VARCHAR(60),
  -- As typed on the form; not a companies reference.
  company_name      VARCHAR(200),
  attachment_remark VARCHAR(500),
  budgeted          VARCHAR(3),
  budgeted_amount   NUMERIC(14,2),
  utilised_amount   NUMERIC(14,2),
  proposed_capex    NUMERIC(14,2),
  balance_amount    NUMERIC(14,2),
  purpose           TEXT,
  CONSTRAINT ck_form_requisition_budgeted CHECK (budgeted IS NULL OR budgeted IN ('yes', 'no'))
);

-- Section C (requested) and Section E (completed by IT) share one shape.
CREATE TABLE IF NOT EXISTS form_requisition_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id  BIGINT        NOT NULL REFERENCES form_requisition (submission_id) ON DELETE CASCADE,
  section        VARCHAR(10)   NOT NULL,
  position       INTEGER       NOT NULL,
  description    TEXT,
  quantity       NUMERIC(12,2),
  unit_price     NUMERIC(14,2),
  CONSTRAINT uq_form_requisition_items UNIQUE (submission_id, section, position),
  CONSTRAINT ck_form_requisition_items_section CHECK (section IN ('requested', 'it'))
);

-- IT Fixed Asset Disposal and IT Fixed Asset Allocation share one table, as
-- they share one on-screen implementation; form_submissions.form_type says which.
CREATE TABLE IF NOT EXISTS form_asset (
  submission_id  BIGINT PRIMARY KEY REFERENCES form_submissions (id) ON DELETE CASCADE,
  employee_id    VARCHAR(60),
  reference_no   VARCHAR(60),
  -- Section D free-text remarks, completed by IT.
  it_remarks     TEXT
);

CREATE TABLE IF NOT EXISTS form_asset_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id  BIGINT        NOT NULL REFERENCES form_asset (submission_id) ON DELETE CASCADE,
  position       INTEGER       NOT NULL,
  description    TEXT,
  spec_model     VARCHAR(200),
  serial_number  VARCHAR(120),
  quantity       NUMERIC(12,2),
  remarks        TEXT,
  CONSTRAINT uq_form_asset_items UNIQUE (submission_id, position)
);

-- Section D tick-box clauses, referenced by id rather than position. Text is
-- reproduced verbatim from company documents; a clause with an emphasised
-- word keeps it as a separate segment (before / emphasis / after).
CREATE TABLE IF NOT EXISTS form_asset_return_options (
  id             VARCHAR(40)  PRIMARY KEY,
  form_type      VARCHAR(12)  NOT NULL,
  text_before    VARCHAR(300) NOT NULL,
  text_emphasis  VARCHAR(60),
  text_after     VARCHAR(300),
  sort_order     INTEGER      NOT NULL DEFAULT 0,
  active         BOOLEAN      NOT NULL DEFAULT TRUE,
  CONSTRAINT ck_form_asset_return_options_type CHECK (form_type IN ('disposal', 'allocation'))
);

CREATE TABLE IF NOT EXISTS form_asset_returns (
  submission_id  BIGINT      NOT NULL REFERENCES form_asset (submission_id) ON DELETE CASCADE,
  option_id      VARCHAR(40) NOT NULL REFERENCES form_asset_return_options (id),
  PRIMARY KEY (submission_id, option_id)
);


-- -----------------------------------------------------------------------------
-- SHARED
-- -----------------------------------------------------------------------------

-- File metadata. The bytes stay in storage (Supabase bucket ticket-attachments,
-- or the server's local folder). Each file belongs to exactly one ticket or
-- one form submission.
CREATE TABLE IF NOT EXISTS attachments (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- The storage object key, also used in the download URL.
  storage_key         VARCHAR(200) NOT NULL UNIQUE,
  ticket_id           BIGINT       REFERENCES tickets (id) ON DELETE CASCADE,
  form_submission_id  BIGINT       REFERENCES form_submissions (id) ON DELETE CASCADE,
  file_name           VARCHAR(260) NOT NULL,
  size_bytes          BIGINT       NOT NULL DEFAULT 0,
  content_type        VARCHAR(150),
  storage_backend     VARCHAR(10)  NOT NULL DEFAULT 'supabase',
  uploaded_at         TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_attachments_backend CHECK (storage_backend IN ('supabase', 'local')),
  CONSTRAINT ck_attachments_one_parent CHECK (
       (ticket_id IS NOT NULL AND form_submission_id IS NULL)
    OR (ticket_id IS NULL     AND form_submission_id IS NOT NULL)
  )
);

-- Workspace settings shared by the whole IT team: a single row (id = 1).
-- Per-browser preferences (theme) and retired options are not stored here;
-- ticket numbering lives in ticket_sequences.
CREATE TABLE IF NOT EXISTS settings (
  id                                  INTEGER     PRIMARY KEY,
  default_view                        VARCHAR(16) NOT NULL DEFAULT 'kanban',
  show_kanban                         BOOLEAN     NOT NULL DEFAULT TRUE,
  show_list                           BOOLEAN     NOT NULL DEFAULT TRUE,
  show_history                        BOOLEAN     NOT NULL DEFAULT TRUE,
  show_handbook                       BOOLEAN     NOT NULL DEFAULT TRUE,
  show_analytics                      BOOLEAN     NOT NULL DEFAULT TRUE,
  show_forms                          BOOLEAN     NOT NULL DEFAULT TRUE,
  show_form_history                   BOOLEAN     NOT NULL DEFAULT TRUE,
  completed_ticket_retention_minutes  INTEGER     NOT NULL DEFAULT 60,
  chat_knowledge_mode                 VARCHAR(8)  NOT NULL DEFAULT 'scoped',
  default_category_id                 BIGINT      REFERENCES categories (id),
  -- Default assignee name for tickets an admin creates.
  operator_name                       VARCHAR(200),
  updated_at                          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_settings_single_row CHECK (id = 1),
  CONSTRAINT ck_settings_default_view CHECK (default_view IN ('kanban', 'list', 'history', 'handbook', 'analytics', 'forms', 'formHistory')),
  CONSTRAINT ck_settings_chat_mode CHECK (chat_knowledge_mode IN ('scoped', 'full')),
  CONSTRAINT ck_settings_retention CHECK (completed_ticket_retention_minutes > 0)
);


-- -----------------------------------------------------------------------------
-- INDEXES
-- -----------------------------------------------------------------------------
-- Ticket and form indexes lead with company_id: reports and lists filter by
-- company first.

CREATE INDEX IF NOT EXISTS ix_tickets_company_status     ON tickets (company_id, status);
CREATE INDEX IF NOT EXISTS ix_tickets_company_created    ON tickets (company_id, created_at);
CREATE INDEX IF NOT EXISTS ix_tickets_company_category   ON tickets (company_id, category_id);
CREATE INDEX IF NOT EXISTS ix_tickets_company_site       ON tickets (company_id, site_id);
CREATE INDEX IF NOT EXISTS ix_tickets_assignee_status    ON tickets (assignee_id, status);
CREATE INDEX IF NOT EXISTS ix_tickets_requester          ON tickets (requester_id);
CREATE INDEX IF NOT EXISTS ix_ticket_status_history_ticket ON ticket_status_history (ticket_id, changed_at);

CREATE INDEX IF NOT EXISTS ix_form_submissions_company_type      ON form_submissions (company_id, form_type, submitted_at);
CREATE INDEX IF NOT EXISTS ix_form_submissions_company_submitter ON form_submissions (company_id, submitted_by_id);
CREATE INDEX IF NOT EXISTS ix_form_submissions_company_site      ON form_submissions (company_id, site_id);
CREATE INDEX IF NOT EXISTS ix_form_asset_items_serial            ON form_asset_items (serial_number);

CREATE INDEX IF NOT EXISTS ix_runbooks_status_category_scope ON runbooks (status, category_id, scope);
CREATE INDEX IF NOT EXISTS ix_runbook_tags_tag               ON runbook_tags (tag);
CREATE INDEX IF NOT EXISTS ix_runbook_related_tickets_ticket ON runbook_related_tickets (ticket_id);

CREATE INDEX IF NOT EXISTS ix_attachments_ticket ON attachments (ticket_id);
CREATE INDEX IF NOT EXISTS ix_attachments_form   ON attachments (form_submission_id);
CREATE INDEX IF NOT EXISTS ix_app_users_company  ON app_users (company_id);
CREATE INDEX IF NOT EXISTS ix_sites_company      ON sites (company_id);


-- -----------------------------------------------------------------------------
-- SEED DATA
-- -----------------------------------------------------------------------------
-- Inserted only when missing, so re-running never duplicates and never
-- overwrites a row an admin has since edited.

-- The current IT_CATEGORIES list (src/types.ts), group-wide, in display order.
INSERT INTO categories (name, sort_order) SELECT 'E-mail', 1                  WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'E-mail');
INSERT INTO categories (name, sort_order) SELECT 'FTP', 2                     WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'FTP');
INSERT INTO categories (name, sort_order) SELECT 'NAV', 3                     WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'NAV');
INSERT INTO categories (name, sort_order) SELECT 'File Server', 4             WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'File Server');
INSERT INTO categories (name, sort_order) SELECT 'Internet', 5                WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Internet');
INSERT INTO categories (name, sort_order) SELECT 'Advance Retails System', 6  WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Advance Retails System');
INSERT INTO categories (name, sort_order) SELECT 'Network', 7                 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Network');
INSERT INTO categories (name, sort_order) SELECT 'HRIS', 8                    WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'HRIS');
INSERT INTO categories (name, sort_order) SELECT 'Ebuilder', 9                WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Ebuilder');
INSERT INTO categories (name, sort_order) SELECT 'Printer', 10                WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Printer');
INSERT INTO categories (name, sort_order) SELECT 'Database', 11               WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Database');
INSERT INTO categories (name, sort_order) SELECT 'Others', 12                 WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name = 'Others');

-- User ID form systems (SERVER_REQUEST_ROWS in src/utils/userIdFormPdf.ts).
-- The ids are the keys stored in every existing submission.
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'email', 'Email', FALSE, 1                                    WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'email');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'doc-control', 'Doc. Control (QM)', FALSE, 2                  WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'doc-control');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'nav', 'NAV', FALSE, 3                                        WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'nav');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'file-server', 'File Server', FALSE, 4                        WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'file-server');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'internet', 'Internet', FALSE, 5                              WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'internet');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'advance-retails', 'Advance Retails System', FALSE, 6         WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'advance-retails');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'network', 'Network', FALSE, 7                                WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'network');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'hris', 'HRIS', FALSE, 8                                      WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'hris');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'ebuilder', 'Ebuilder', FALSE, 9                              WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'ebuilder');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'printer', 'Printer', FALSE, 10                               WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'printer');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'database', 'Database', FALSE, 11                             WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'database');
INSERT INTO form_system_options (id, label, has_free_text, sort_order) SELECT 'others', 'Others:', TRUE, 12                                 WHERE NOT EXISTS (SELECT 1 FROM form_system_options WHERE id = 'others');

-- Allocation form Section D, verbatim from ALLOCATION_FORM.sectionD in
-- src/utils/assetFormPdf.ts (added 11092026ver017). The second clause's NOT is
-- printed bold, so it is its own segment. The disposal form has no Section D.
INSERT INTO form_asset_return_options (id, form_type, text_before, text_emphasis, text_after, sort_order)
  SELECT 'allocation-returned-good', 'allocation', '1. Allocated units returned as stated above in good condition.', NULL, NULL, 1
  WHERE NOT EXISTS (SELECT 1 FROM form_asset_return_options WHERE id = 'allocation-returned-good');
INSERT INTO form_asset_return_options (id, form_type, text_before, text_emphasis, text_after, sort_order)
  SELECT 'allocation-returned-not-good', 'allocation', '2. Allocated units returned as stated above', 'NOT', 'in good condition.', 2
  WHERE NOT EXISTS (SELECT 1 FROM form_asset_return_options WHERE id = 'allocation-returned-not-good');


-- -----------------------------------------------------------------------------
-- SUPABASE ONLY (omit on other engines)
-- -----------------------------------------------------------------------------
-- Supabase publishes every public table through its REST API, where the anon
-- key in any browser could otherwise read and write them. Enabling row level
-- security with no policies closes that door; the server's service-role key
-- bypasses it. This is not a per-company rule: every table is either fully
-- reachable by the server or not reachable by browsers at all.
ALTER TABLE companies                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites                     ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories                ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbooks                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_tags              ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_trigger_patterns  ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_diagnostic_steps  ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_remediation_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_postmortem_items  ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_review_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE runbook_related_tickets   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_sequences          ENABLE ROW LEVEL SECURITY;
ALTER TABLE tickets                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_tags               ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_checklist_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_status_history     ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_submissions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_user_id              ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_system_options       ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_user_id_systems      ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_requisition          ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_requisition_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_asset                ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_asset_items          ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_asset_return_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE form_asset_returns        ENABLE ROW LEVEL SECURITY;
ALTER TABLE attachments               ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings                  ENABLE ROW LEVEL SECURITY;

-- Make the new tables visible to the REST API straight away.
NOTIFY pgrst, 'reload schema';
